OIDC Support
lamassuiot/lamassu-ui pull request #9
Opened 2023-06-22 12:23 UTC by haritzsaiz

Removing keycloak-dependant component for authenticating users. Refactored code to use more generic authentication approach using OIDC standard.

Some AWS Cognito specific implementation was done to adjust the logout experience since cognito doesn't implement the `end_session_endpoint` as specified by the standard

2023-06-23 14:57 UTC, jjrodrig requested changes
Thanks for the PR.
In general is Ok but please remove unnecesary logging, comments and internal development configs.

2023-06-23 14:57 UTC, jjrodrig commented on public/env-config.js
Could this file be replaced by a blank config in stead of a local development configuration?

We should avoid to push internal configs into the main repo.

2023-06-23 14:57 UTC, jjrodrig commented on src/App.tsx
> +// console.log(oidc.Version);
Please remove commented logging code

2023-06-23 14:57 UTC, jjrodrig commented on src/views/AlertsView/SubscribeDialog.tsx
> +            console.log(auth.user);
Is this log useful?

2023-06-26 05:45 UTC, haritzsaiz commented
I've updated the pr with the comments you mentioned

2023-06-26 06:30 UTC, jjrodrig requested changes

2023-06-26 06:30 UTC, jjrodrig commented on src/ducks/services/api/token.ts
>      console.log("b");
This log seems not to be useful, can we remove it?

2023-06-26 07:21 UTC, jjrodrig approved these changes

2023-06-26 07:23 UTC, merged